/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bar': RouteRecordInfo<'/bar', '/bar', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/podcasts': RouteRecordInfo<'/podcasts', '/podcasts', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/about-yak-shaving': RouteRecordInfo<'/posts/about-yak-shaving', '/posts/about-yak-shaving', Record<never, never>, Record<never, never>>,
    '/posts/about-yak-shaving-zh': RouteRecordInfo<'/posts/about-yak-shaving-zh', '/posts/about-yak-shaving-zh', Record<never, never>, Record<never, never>>,
    '/posts/ai-qrcode': RouteRecordInfo<'/posts/ai-qrcode', '/posts/ai-qrcode', Record<never, never>, Record<never, never>>,
    '/posts/ai-qrcode-101': RouteRecordInfo<'/posts/ai-qrcode-101', '/posts/ai-qrcode-101', Record<never, never>, Record<never, never>>,
    '/posts/ai-qrcode-refine': RouteRecordInfo<'/posts/ai-qrcode-refine', '/posts/ai-qrcode-refine', Record<never, never>, Record<never, never>>,
    '/posts/animated-svg-logo': RouteRecordInfo<'/posts/animated-svg-logo', '/posts/animated-svg-logo', Record<never, never>, Record<never, never>>,
    '/posts/async-sync-in-between': RouteRecordInfo<'/posts/async-sync-in-between', '/posts/async-sync-in-between', Record<never, never>, Record<never, never>>,
    '/posts/async-with-composition-api': RouteRecordInfo<'/posts/async-with-composition-api', '/posts/async-with-composition-api', Record<never, never>, Record<never, never>>,
    '/posts/binfe-2020-zh': RouteRecordInfo<'/posts/binfe-2020-zh', '/posts/binfe-2020-zh', Record<never, never>, Record<never, never>>,
    '/posts/bonjour-paris': RouteRecordInfo<'/posts/bonjour-paris', '/posts/bonjour-paris', Record<never, never>, Record<never, never>>,
    '/posts/break-lines-in-js': RouteRecordInfo<'/posts/break-lines-in-js', '/posts/break-lines-in-js', Record<never, never>, Record<never, never>>,
    '/posts/categorize-deps': RouteRecordInfo<'/posts/categorize-deps', '/posts/categorize-deps', Record<never, never>, Record<never, never>>,
    '/posts/color-scheme-for-vscode-ext': RouteRecordInfo<'/posts/color-scheme-for-vscode-ext', '/posts/color-scheme-for-vscode-ext', Record<never, never>, Record<never, never>>,
    '/posts/composable-vue-vueconf-china-2021': RouteRecordInfo<'/posts/composable-vue-vueconf-china-2021', '/posts/composable-vue-vueconf-china-2021', Record<never, never>, Record<never, never>>,
    '/posts/composable-vue-vueday-2021': RouteRecordInfo<'/posts/composable-vue-vueday-2021', '/posts/composable-vue-vueday-2021', Record<never, never>, Record<never, never>>,
    '/posts/destructuring-with-object-or-array': RouteRecordInfo<'/posts/destructuring-with-object-or-array', '/posts/destructuring-with-object-or-array', Record<never, never>, Record<never, never>>,
    '/posts/dev-ssr-on-nuxt': RouteRecordInfo<'/posts/dev-ssr-on-nuxt', '/posts/dev-ssr-on-nuxt', Record<never, never>, Record<never, never>>,
    '/posts/domain-email': RouteRecordInfo<'/posts/domain-email', '/posts/domain-email', Record<never, never>, Record<never, never>>,
    '/posts/epoch-semver': RouteRecordInfo<'/posts/epoch-semver', '/posts/epoch-semver', Record<never, never>, Record<never, never>>,
    '/posts/eslint-config-inspector': RouteRecordInfo<'/posts/eslint-config-inspector', '/posts/eslint-config-inspector', Record<never, never>, Record<never, never>>,
    '/posts/evolution-of-shiki-v1': RouteRecordInfo<'/posts/evolution-of-shiki-v1', '/posts/evolution-of-shiki-v1', Record<never, never>, Record<never, never>>,
    '/posts/get-package-root': RouteRecordInfo<'/posts/get-package-root', '/posts/get-package-root', Record<never, never>, Record<never, never>>,
    '/posts/github-alerts': RouteRecordInfo<'/posts/github-alerts', '/posts/github-alerts', Record<never, never>, Record<never, never>>,
    '/posts/github-co-authors': RouteRecordInfo<'/posts/github-co-authors', '/posts/github-co-authors', Record<never, never>, Record<never, never>>,
    '/posts/hello-tokyo': RouteRecordInfo<'/posts/hello-tokyo', '/posts/hello-tokyo', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css': RouteRecordInfo<'/posts/icons-in-pure-css', '/posts/icons-in-pure-css', Record<never, never>, Record<never, never>>,
    '/posts/icons-in-pure-css-zh': RouteRecordInfo<'/posts/icons-in-pure-css-zh', '/posts/icons-in-pure-css-zh', Record<never, never>, Record<never, never>>,
    '/posts/introducing-nuxt-devtools': RouteRecordInfo<'/posts/introducing-nuxt-devtools', '/posts/introducing-nuxt-devtools', Record<never, never>, Record<never, never>>,
    '/posts/introduction-to-vitest-vue-nation-2022': RouteRecordInfo<'/posts/introduction-to-vitest-vue-nation-2022', '/posts/introduction-to-vitest-vue-nation-2022', Record<never, never>, Record<never, never>>,
    '/posts/isomorphic-dirname': RouteRecordInfo<'/posts/isomorphic-dirname', '/posts/isomorphic-dirname', Record<never, never>, Record<never, never>>,
    '/posts/journey-with-icons': RouteRecordInfo<'/posts/journey-with-icons', '/posts/journey-with-icons', Record<never, never>, Record<never, never>>,
    '/posts/journey-with-icons-continues': RouteRecordInfo<'/posts/journey-with-icons-continues', '/posts/journey-with-icons-continues', Record<never, never>, Record<never, never>>,
    '/posts/make-libraries-working-with-vue-2-and-3': RouteRecordInfo<'/posts/make-libraries-working-with-vue-2-and-3', '/posts/make-libraries-working-with-vue-2-and-3', Record<never, never>, Record<never, never>>,
    '/posts/manage-github-notifications-2023': RouteRecordInfo<'/posts/manage-github-notifications-2023', '/posts/manage-github-notifications-2023', Record<never, never>, Record<never, never>>,
    '/posts/match-chinese-characters': RouteRecordInfo<'/posts/match-chinese-characters', '/posts/match-chinese-characters', Record<never, never>, Record<never, never>>,
    '/posts/match-quotes-in-pairs': RouteRecordInfo<'/posts/match-quotes-in-pairs', '/posts/match-quotes-in-pairs', Record<never, never>, Record<never, never>>,
    '/posts/mental-health-oss': RouteRecordInfo<'/posts/mental-health-oss', '/posts/mental-health-oss', Record<never, never>, Record<never, never>>,
    '/posts/mental-health-oss-zh': RouteRecordInfo<'/posts/mental-health-oss-zh', '/posts/mental-health-oss-zh', Record<never, never>, Record<never, never>>,
    '/posts/move-on-to-esm-only': RouteRecordInfo<'/posts/move-on-to-esm-only', '/posts/move-on-to-esm-only', Record<never, never>, Record<never, never>>,
    '/posts/netlify-redirects': RouteRecordInfo<'/posts/netlify-redirects', '/posts/netlify-redirects', Record<never, never>, Record<never, never>>,
    '/posts/new-house': RouteRecordInfo<'/posts/new-house', '/posts/new-house', Record<never, never>, Record<never, never>>,
    '/posts/new-ways-to-vue-london-2021': RouteRecordInfo<'/posts/new-ways-to-vue-london-2021', '/posts/new-ways-to-vue-london-2021', Record<never, never>, Record<never, never>>,
    '/posts/new-ways-to-vue-taiwan-2021': RouteRecordInfo<'/posts/new-ways-to-vue-taiwan-2021', '/posts/new-ways-to-vue-taiwan-2021', Record<never, never>, Record<never, never>>,
    '/posts/now-and-future-devtools-nuxt-nation-2023': RouteRecordInfo<'/posts/now-and-future-devtools-nuxt-nation-2023', '/posts/now-and-future-devtools-nuxt-nation-2023', Record<never, never>, Record<never, never>>,
    '/posts/npm-binary-mirrors': RouteRecordInfo<'/posts/npm-binary-mirrors', '/posts/npm-binary-mirrors', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-cpuprofile': RouteRecordInfo<'/posts/nuxt-cpuprofile', '/posts/nuxt-cpuprofile', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-devtools-v1': RouteRecordInfo<'/posts/nuxt-devtools-v1', '/posts/nuxt-devtools-v1', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-dx-2023': RouteRecordInfo<'/posts/nuxt-dx-2023', '/posts/nuxt-dx-2023', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-dx-strasbourg-2023': RouteRecordInfo<'/posts/nuxt-dx-strasbourg-2023', '/posts/nuxt-dx-strasbourg-2023', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-icon-v1': RouteRecordInfo<'/posts/nuxt-icon-v1', '/posts/nuxt-icon-v1', Record<never, never>, Record<never, never>>,
    '/posts/ohayo-tokyo': RouteRecordInfo<'/posts/ohayo-tokyo', '/posts/ohayo-tokyo', Record<never, never>, Record<never, never>>,
    '/posts/optimize-await': RouteRecordInfo<'/posts/optimize-await', '/posts/optimize-await', Record<never, never>, Record<never, never>>,
    '/posts/patterns-of-vueuse-vuefes-japan-2022': RouteRecordInfo<'/posts/patterns-of-vueuse-vuefes-japan-2022', '/posts/patterns-of-vueuse-vuefes-japan-2022', Record<never, never>, Record<never, never>>,
    '/posts/photos-page': RouteRecordInfo<'/posts/photos-page', '/posts/photos-page', Record<never, never>, Record<never, never>>,
    '/posts/pnpm-external-disk': RouteRecordInfo<'/posts/pnpm-external-disk', '/posts/pnpm-external-disk', Record<never, never>, Record<never, never>>,
    '/posts/publish-esm-and-cjs': RouteRecordInfo<'/posts/publish-esm-and-cjs', '/posts/publish-esm-and-cjs', Record<never, never>, Record<never, never>>,
    '/posts/range-in-javascript': RouteRecordInfo<'/posts/range-in-javascript', '/posts/range-in-javascript', Record<never, never>, Record<never, never>>,
    '/posts/reflection-of-speaking-in-public': RouteRecordInfo<'/posts/reflection-of-speaking-in-public', '/posts/reflection-of-speaking-in-public', Record<never, never>, Record<never, never>>,
    '/posts/refreshed-nuxt-eslint': RouteRecordInfo<'/posts/refreshed-nuxt-eslint', '/posts/refreshed-nuxt-eslint', Record<never, never>, Record<never, never>>,
    '/posts/reimagine-atomic-css': RouteRecordInfo<'/posts/reimagine-atomic-css', '/posts/reimagine-atomic-css', Record<never, never>, Record<never, never>>,
    '/posts/reimagine-atomic-css-zh': RouteRecordInfo<'/posts/reimagine-atomic-css-zh', '/posts/reimagine-atomic-css-zh', Record<never, never>, Record<never, never>>,
    '/posts/rewrite-in-vite': RouteRecordInfo<'/posts/rewrite-in-vite', '/posts/rewrite-in-vite', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-progressive-vueams-2024': RouteRecordInfo<'/posts/roads-to-oss-progressive-vueams-2024', '/posts/roads-to-oss-progressive-vueams-2024', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-react-paris-2024': RouteRecordInfo<'/posts/roads-to-oss-set-theory-react-paris-2024', '/posts/roads-to-oss-set-theory-react-paris-2024', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-viteconf-2023': RouteRecordInfo<'/posts/roads-to-oss-set-theory-viteconf-2023', '/posts/roads-to-oss-set-theory-viteconf-2023', Record<never, never>, Record<never, never>>,
    '/posts/roads-to-oss-set-theory-vuefesjapan-2023': RouteRecordInfo<'/posts/roads-to-oss-set-theory-vuefesjapan-2023', '/posts/roads-to-oss-set-theory-vuefesjapan-2023', Record<never, never>, Record<never, never>>,
    '/posts/shiki-magic-move': RouteRecordInfo<'/posts/shiki-magic-move', '/posts/shiki-magic-move', Record<never, never>, Record<never, never>>,
    '/posts/shikiji-twoslash': RouteRecordInfo<'/posts/shikiji-twoslash', '/posts/shikiji-twoslash', Record<never, never>, Record<never, never>>,
    '/posts/sliding-enter-animation': RouteRecordInfo<'/posts/sliding-enter-animation', '/posts/sliding-enter-animation', Record<never, never>, Record<never, never>>,
    '/posts/sponsorship-forwarding': RouteRecordInfo<'/posts/sponsorship-forwarding', '/posts/sponsorship-forwarding', Record<never, never>, Record<never, never>>,
    '/posts/type-inferencing-in-vue': RouteRecordInfo<'/posts/type-inferencing-in-vue', '/posts/type-inferencing-in-vue', Record<never, never>, Record<never, never>>,
    '/posts/type-your-config': RouteRecordInfo<'/posts/type-your-config', '/posts/type-your-config', Record<never, never>, Record<never, never>>,
    '/posts/typed-provide-and-inject-in-vue': RouteRecordInfo<'/posts/typed-provide-and-inject-in-vue', '/posts/typed-provide-and-inject-in-vue', Record<never, never>, Record<never, never>>,
    '/posts/types-for-sub-modules': RouteRecordInfo<'/posts/types-for-sub-modules', '/posts/types-for-sub-modules', Record<never, never>, Record<never, never>>,
    '/posts/vite-on-demand-dx-viteconf-2022': RouteRecordInfo<'/posts/vite-on-demand-dx-viteconf-2022', '/posts/vite-on-demand-dx-viteconf-2022', Record<never, never>, Record<never, never>>,
    '/posts/vue-3-notes': RouteRecordInfo<'/posts/vue-3-notes', '/posts/vue-3-notes', Record<never, never>, Record<never, never>>,
    '/posts/vue-beijing-2021': RouteRecordInfo<'/posts/vue-beijing-2021', '/posts/vue-beijing-2021', Record<never, never>, Record<never, never>>,
    '/posts/vueuse-best-practice-vueconf-china-2022': RouteRecordInfo<'/posts/vueuse-best-practice-vueconf-china-2022', '/posts/vueuse-best-practice-vueconf-china-2022', Record<never, never>, Record<never, never>>,
    '/posts/watch-with-reactivity': RouteRecordInfo<'/posts/watch-with-reactivity', '/posts/watch-with-reactivity', Record<never, never>, Record<never, never>>,
    '/posts/why-not-prettier': RouteRecordInfo<'/posts/why-not-prettier', '/posts/why-not-prettier', Record<never, never>, Record<never, never>>,
    '/posts/why-not-prettier-zh': RouteRecordInfo<'/posts/why-not-prettier-zh', '/posts/why-not-prettier-zh', Record<never, never>, Record<never, never>>,
    '/posts/why-reproductions-are-required': RouteRecordInfo<'/posts/why-reproductions-are-required', '/posts/why-reproductions-are-required', Record<never, never>, Record<never, never>>,
    '/posts/why-reproductions-are-required-zh': RouteRecordInfo<'/posts/why-reproductions-are-required-zh', '/posts/why-reproductions-are-required-zh', Record<never, never>, Record<never, never>>,
    '/posts/windicss-and-tailwind-jit': RouteRecordInfo<'/posts/windicss-and-tailwind-jit', '/posts/windicss-and-tailwind-jit', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'pages/[...404].md': {
      routes: '/[...404]'
      views: never
    }
    'pages/bar.md': {
      routes: '/bar'
      views: never
    }
    'pages/bookmarks.md': {
      routes: '/bookmarks'
      views: never
    }
    'pages/chat.md': {
      routes: '/chat'
      views: never
    }
    'pages/chat-zh.md': {
      routes: '/chat-zh'
      views: never
    }
    'pages/collective-sponsor-onetime.md': {
      routes: '/collective-sponsor-onetime'
      views: never
    }
    'pages/demos.md': {
      routes: '/demos'
      views: never
    }
    'pages/giving-talks.md': {
      routes: '/giving-talks'
      views: never
    }
    'pages/media.md': {
      routes: '/media'
      views: never
    }
    'pages/notes.md': {
      routes: '/notes'
      views: never
    }
    'pages/photos.md': {
      routes: '/photos'
      views: never
    }
    'pages/podcasts.md': {
      routes: '/podcasts'
      views: never
    }
    'pages/posts/index.md': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/about-yak-shaving.md': {
      routes: '/posts/about-yak-shaving'
      views: never
    }
    'pages/posts/about-yak-shaving-zh.md': {
      routes: '/posts/about-yak-shaving-zh'
      views: never
    }
    'pages/posts/ai-qrcode.md': {
      routes: '/posts/ai-qrcode'
      views: never
    }
    'pages/posts/ai-qrcode-101.md': {
      routes: '/posts/ai-qrcode-101'
      views: never
    }
    'pages/posts/ai-qrcode-refine.md': {
      routes: '/posts/ai-qrcode-refine'
      views: never
    }
    'pages/posts/animated-svg-logo.md': {
      routes: '/posts/animated-svg-logo'
      views: never
    }
    'pages/posts/async-sync-in-between.md': {
      routes: '/posts/async-sync-in-between'
      views: never
    }
    'pages/posts/async-with-composition-api.md': {
      routes: '/posts/async-with-composition-api'
      views: never
    }
    'pages/posts/binfe-2020-zh.md': {
      routes: '/posts/binfe-2020-zh'
      views: never
    }
    'pages/posts/bonjour-paris.md': {
      routes: '/posts/bonjour-paris'
      views: never
    }
    'pages/posts/break-lines-in-js.md': {
      routes: '/posts/break-lines-in-js'
      views: never
    }
    'pages/posts/categorize-deps.md': {
      routes: '/posts/categorize-deps'
      views: never
    }
    'pages/posts/color-scheme-for-vscode-ext.md': {
      routes: '/posts/color-scheme-for-vscode-ext'
      views: never
    }
    'pages/posts/composable-vue-vueconf-china-2021.md': {
      routes: '/posts/composable-vue-vueconf-china-2021'
      views: never
    }
    'pages/posts/composable-vue-vueday-2021.md': {
      routes: '/posts/composable-vue-vueday-2021'
      views: never
    }
    'pages/posts/destructuring-with-object-or-array.md': {
      routes: '/posts/destructuring-with-object-or-array'
      views: never
    }
    'pages/posts/dev-ssr-on-nuxt.md': {
      routes: '/posts/dev-ssr-on-nuxt'
      views: never
    }
    'pages/posts/domain-email.md': {
      routes: '/posts/domain-email'
      views: never
    }
    'pages/posts/epoch-semver.md': {
      routes: '/posts/epoch-semver'
      views: never
    }
    'pages/posts/eslint-config-inspector.md': {
      routes: '/posts/eslint-config-inspector'
      views: never
    }
    'pages/posts/evolution-of-shiki-v1.md': {
      routes: '/posts/evolution-of-shiki-v1'
      views: never
    }
    'pages/posts/get-package-root.md': {
      routes: '/posts/get-package-root'
      views: never
    }
    'pages/posts/github-alerts.md': {
      routes: '/posts/github-alerts'
      views: never
    }
    'pages/posts/github-co-authors.md': {
      routes: '/posts/github-co-authors'
      views: never
    }
    'pages/posts/hello-tokyo.md': {
      routes: '/posts/hello-tokyo'
      views: never
    }
    'pages/posts/icons-in-pure-css.md': {
      routes: '/posts/icons-in-pure-css'
      views: never
    }
    'pages/posts/icons-in-pure-css-zh.md': {
      routes: '/posts/icons-in-pure-css-zh'
      views: never
    }
    'pages/posts/introducing-nuxt-devtools.md': {
      routes: '/posts/introducing-nuxt-devtools'
      views: never
    }
    'pages/posts/introduction-to-vitest-vue-nation-2022.md': {
      routes: '/posts/introduction-to-vitest-vue-nation-2022'
      views: never
    }
    'pages/posts/isomorphic-dirname.md': {
      routes: '/posts/isomorphic-dirname'
      views: never
    }
    'pages/posts/journey-with-icons.md': {
      routes: '/posts/journey-with-icons'
      views: never
    }
    'pages/posts/journey-with-icons-continues.md': {
      routes: '/posts/journey-with-icons-continues'
      views: never
    }
    'pages/posts/make-libraries-working-with-vue-2-and-3.md': {
      routes: '/posts/make-libraries-working-with-vue-2-and-3'
      views: never
    }
    'pages/posts/manage-github-notifications-2023.md': {
      routes: '/posts/manage-github-notifications-2023'
      views: never
    }
    'pages/posts/match-chinese-characters.md': {
      routes: '/posts/match-chinese-characters'
      views: never
    }
    'pages/posts/match-quotes-in-pairs.md': {
      routes: '/posts/match-quotes-in-pairs'
      views: never
    }
    'pages/posts/mental-health-oss.md': {
      routes: '/posts/mental-health-oss'
      views: never
    }
    'pages/posts/mental-health-oss-zh.md': {
      routes: '/posts/mental-health-oss-zh'
      views: never
    }
    'pages/posts/move-on-to-esm-only.md': {
      routes: '/posts/move-on-to-esm-only'
      views: never
    }
    'pages/posts/netlify-redirects.md': {
      routes: '/posts/netlify-redirects'
      views: never
    }
    'pages/posts/new-house.md': {
      routes: '/posts/new-house'
      views: never
    }
    'pages/posts/new-ways-to-vue-london-2021.md': {
      routes: '/posts/new-ways-to-vue-london-2021'
      views: never
    }
    'pages/posts/new-ways-to-vue-taiwan-2021.md': {
      routes: '/posts/new-ways-to-vue-taiwan-2021'
      views: never
    }
    'pages/posts/now-and-future-devtools-nuxt-nation-2023.md': {
      routes: '/posts/now-and-future-devtools-nuxt-nation-2023'
      views: never
    }
    'pages/posts/npm-binary-mirrors.md': {
      routes: '/posts/npm-binary-mirrors'
      views: never
    }
    'pages/posts/nuxt-cpuprofile.md': {
      routes: '/posts/nuxt-cpuprofile'
      views: never
    }
    'pages/posts/nuxt-devtools-v1.md': {
      routes: '/posts/nuxt-devtools-v1'
      views: never
    }
    'pages/posts/nuxt-dx-2023.md': {
      routes: '/posts/nuxt-dx-2023'
      views: never
    }
    'pages/posts/nuxt-dx-strasbourg-2023.md': {
      routes: '/posts/nuxt-dx-strasbourg-2023'
      views: never
    }
    'pages/posts/nuxt-icon-v1.md': {
      routes: '/posts/nuxt-icon-v1'
      views: never
    }
    'pages/posts/ohayo-tokyo.md': {
      routes: '/posts/ohayo-tokyo'
      views: never
    }
    'pages/posts/optimize-await.md': {
      routes: '/posts/optimize-await'
      views: never
    }
    'pages/posts/patterns-of-vueuse-vuefes-japan-2022.md': {
      routes: '/posts/patterns-of-vueuse-vuefes-japan-2022'
      views: never
    }
    'pages/posts/photos-page.md': {
      routes: '/posts/photos-page'
      views: never
    }
    'pages/posts/pnpm-external-disk.md': {
      routes: '/posts/pnpm-external-disk'
      views: never
    }
    'pages/posts/publish-esm-and-cjs.md': {
      routes: '/posts/publish-esm-and-cjs'
      views: never
    }
    'pages/posts/range-in-javascript.md': {
      routes: '/posts/range-in-javascript'
      views: never
    }
    'pages/posts/reflection-of-speaking-in-public.md': {
      routes: '/posts/reflection-of-speaking-in-public'
      views: never
    }
    'pages/posts/refreshed-nuxt-eslint.md': {
      routes: '/posts/refreshed-nuxt-eslint'
      views: never
    }
    'pages/posts/reimagine-atomic-css.md': {
      routes: '/posts/reimagine-atomic-css'
      views: never
    }
    'pages/posts/reimagine-atomic-css-zh.md': {
      routes: '/posts/reimagine-atomic-css-zh'
      views: never
    }
    'pages/posts/rewrite-in-vite.md': {
      routes: '/posts/rewrite-in-vite'
      views: never
    }
    'pages/posts/roads-to-oss-progressive-vueams-2024.md': {
      routes: '/posts/roads-to-oss-progressive-vueams-2024'
      views: never
    }
    'pages/posts/roads-to-oss-set-theory-react-paris-2024.md': {
      routes: '/posts/roads-to-oss-set-theory-react-paris-2024'
      views: never
    }
    'pages/posts/roads-to-oss-set-theory-viteconf-2023.md': {
      routes: '/posts/roads-to-oss-set-theory-viteconf-2023'
      views: never
    }
    'pages/posts/roads-to-oss-set-theory-vuefesjapan-2023.md': {
      routes: '/posts/roads-to-oss-set-theory-vuefesjapan-2023'
      views: never
    }
    'pages/posts/shiki-magic-move.md': {
      routes: '/posts/shiki-magic-move'
      views: never
    }
    'pages/posts/shikiji-twoslash.md': {
      routes: '/posts/shikiji-twoslash'
      views: never
    }
    'pages/posts/sliding-enter-animation.md': {
      routes: '/posts/sliding-enter-animation'
      views: never
    }
    'pages/posts/sponsorship-forwarding.md': {
      routes: '/posts/sponsorship-forwarding'
      views: never
    }
    'pages/posts/type-inferencing-in-vue.md': {
      routes: '/posts/type-inferencing-in-vue'
      views: never
    }
    'pages/posts/type-your-config.md': {
      routes: '/posts/type-your-config'
      views: never
    }
    'pages/posts/typed-provide-and-inject-in-vue.md': {
      routes: '/posts/typed-provide-and-inject-in-vue'
      views: never
    }
    'pages/posts/types-for-sub-modules.md': {
      routes: '/posts/types-for-sub-modules'
      views: never
    }
    'pages/posts/vite-on-demand-dx-viteconf-2022.md': {
      routes: '/posts/vite-on-demand-dx-viteconf-2022'
      views: never
    }
    'pages/posts/vue-3-notes.md': {
      routes: '/posts/vue-3-notes'
      views: never
    }
    'pages/posts/vue-beijing-2021.md': {
      routes: '/posts/vue-beijing-2021'
      views: never
    }
    'pages/posts/vueuse-best-practice-vueconf-china-2022.md': {
      routes: '/posts/vueuse-best-practice-vueconf-china-2022'
      views: never
    }
    'pages/posts/watch-with-reactivity.md': {
      routes: '/posts/watch-with-reactivity'
      views: never
    }
    'pages/posts/why-not-prettier.md': {
      routes: '/posts/why-not-prettier'
      views: never
    }
    'pages/posts/why-not-prettier-zh.md': {
      routes: '/posts/why-not-prettier-zh'
      views: never
    }
    'pages/posts/why-reproductions-are-required.md': {
      routes: '/posts/why-reproductions-are-required'
      views: never
    }
    'pages/posts/why-reproductions-are-required-zh.md': {
      routes: '/posts/why-reproductions-are-required-zh'
      views: never
    }
    'pages/posts/windicss-and-tailwind-jit.md': {
      routes: '/posts/windicss-and-tailwind-jit'
      views: never
    }
    'pages/projects.md': {
      routes: '/projects'
      views: never
    }
    'pages/sponsors-list.md': {
      routes: '/sponsors-list'
      views: never
    }
    'pages/streams.md': {
      routes: '/streams'
      views: never
    }
    'pages/talks.md': {
      routes: '/talks'
      views: never
    }
    'pages/use.md': {
      routes: '/use'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
