/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/create/': RouteRecordInfo<'/create/', '/create', Record<never, never>, Record<never, never>>,
    '/daily/': RouteRecordInfo<'/daily/', '/daily', Record<never, never>, Record<never, never>>,
    '/design/': RouteRecordInfo<'/design/', '/design', Record<never, never>, Record<never, never>>,
    '/interest/': RouteRecordInfo<'/interest/', '/interest', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/babel-handbook': RouteRecordInfo<'/posts/babel-handbook', '/posts/babel-handbook', Record<never, never>, Record<never, never>>,
    '/posts/babel-type': RouteRecordInfo<'/posts/babel-type', '/posts/babel-type', Record<never, never>, Record<never, never>>,
    '/posts/daily-style-questions': RouteRecordInfo<'/posts/daily-style-questions', '/posts/daily-style-questions', Record<never, never>, Record<never, never>>,
    '/posts/ESM和CommonJS的差异': RouteRecordInfo<'/posts/ESM和CommonJS的差异', '/posts/ESM和CommonJS的差异', Record<never, never>, Record<never, never>>,
    '/posts/ESM的加载': RouteRecordInfo<'/posts/ESM的加载', '/posts/ESM的加载', Record<never, never>, Record<never, never>>,
    '/posts/koa': RouteRecordInfo<'/posts/koa', '/posts/koa', Record<never, never>, Record<never, never>>,
    '/posts/leetcode': RouteRecordInfo<'/posts/leetcode', '/posts/leetcode', Record<never, never>, Record<never, never>>,
    '/posts/node-modularity': RouteRecordInfo<'/posts/node-modularity', '/posts/node-modularity', Record<never, never>, Record<never, never>>,
    '/posts/oauth-2.0': RouteRecordInfo<'/posts/oauth-2.0', '/posts/oauth-2/0', Record<never, never>, Record<never, never>>,
    '/posts/pnpm原理': RouteRecordInfo<'/posts/pnpm原理', '/posts/pnpm原理', Record<never, never>, Record<never, never>>,
    '/posts/React开发过程中需要注意的点': RouteRecordInfo<'/posts/React开发过程中需要注意的点', '/posts/React开发过程中需要注意的点', Record<never, never>, Record<never, never>>,
    '/posts/React整体架构': RouteRecordInfo<'/posts/React整体架构', '/posts/React整体架构', Record<never, never>, Record<never, never>>,
    '/posts/React渲染流程': RouteRecordInfo<'/posts/React渲染流程', '/posts/React渲染流程', Record<never, never>, Record<never, never>>,
    '/posts/React组件渲染性能优化': RouteRecordInfo<'/posts/React组件渲染性能优化', '/posts/React组件渲染性能优化', Record<never, never>, Record<never, never>>,
    '/posts/resolveFactory浅析': RouteRecordInfo<'/posts/resolveFactory浅析', '/posts/resolveFactory浅析', Record<never, never>, Record<never, never>>,
    '/posts/simple-reactive': RouteRecordInfo<'/posts/simple-reactive', '/posts/simple-reactive', Record<never, never>, Record<never, never>>,
    '/posts/structure': RouteRecordInfo<'/posts/structure', '/posts/structure', Record<never, never>, Record<never, never>>,
    '/posts/Vue3.4中.vue文件编译流程图': RouteRecordInfo<'/posts/Vue3.4中.vue文件编译流程图', '/posts/Vue3/4中/vue文件编译流程图', Record<never, never>, Record<never, never>>,
    '/posts/webpack-compiler-hook': RouteRecordInfo<'/posts/webpack-compiler-hook', '/posts/webpack-compiler-hook', Record<never, never>, Record<never, never>>,
    '/posts/虚拟DOM': RouteRecordInfo<'/posts/虚拟DOM', '/posts/虚拟DOM', Record<never, never>, Record<never, never>>,
    '/posts/解构是使用对象还是数组': RouteRecordInfo<'/posts/解构是使用对象还是数组', '/posts/解构是使用对象还是数组', Record<never, never>, Record<never, never>>,
    '/thinking/': RouteRecordInfo<'/thinking/', '/thinking', Record<never, never>, Record<never, never>>,
  }
}
