import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'

interface DailyRecord {
  slug: string
  date: string
  content: string
}

const contentDir = path.join(process.cwd(), 'pages/content/daily')
const outputPath = path.join(process.cwd(), 'src/data/dailiesAuto.ts')

function generateDailies() {
  // Ensure content directory exists
  if (!fs.existsSync(contentDir)) {
    fs.mkdirSync(contentDir, { recursive: true })
    // Create sample file if directory is empty
    const today = new Date()
    const dateStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
    const sampleContent = `---
date: ${dateStr}
---

# 今日碎记

这是今天的碎记内容...`
    fs.writeFileSync(path.join(contentDir, `${dateStr}.md`), sampleContent)
  }

  const files = fs.readdirSync(contentDir).filter(f => f.endsWith('.md'))

  const records: DailyRecord[] = files.map((file) => {
    const filePath = path.join(contentDir, file)
    const content = fs.readFileSync(filePath, 'utf-8')
    const { data, content: body } = matter(content)

    // Format date to YYYY-MM-DD
    let dateStr = data.date || file.replace('.md', '')
    if (dateStr instanceof Date) {
      dateStr = `${dateStr.getFullYear()}-${String(dateStr.getMonth() + 1).padStart(2, '0')}-${String(dateStr.getDate()).padStart(2, '0')}`
    }

    return {
      slug: file.replace('.md', ''),
      date: dateStr,
      content: body.trim(),
    }
  })

  // Sort by date descending
  records.sort((a, b) => b.date.localeCompare(a.date))

  const output = `// Auto-generated by scripts/generateDailies.ts
export interface DailyRecord {
  slug: string
  date: string
  content: string
}

export const dailyRecords: DailyRecord[] = ${JSON.stringify(records, null, 2)}
`

  fs.writeFileSync(outputPath, output, 'utf-8')
  console.log('[generateDailies] Generated dailiesAuto.ts')
}

generateDailies()
