// Auto-generated by scripts/generateDailies.ts
export interface DailyRecord {
  slug: string
  date: string
  content: string
}

export const dailyRecords: DailyRecord[] = [
  {
    slug: '2026-04-01',
    date: '2026-04-01',
    content: '# 今天是个好日子，天气晴朗。\n\n学习了一些新的技术知识，主要是关于 Vue 3 的响应式原理。\n晚上和朋友吃了一顿火锅，很开心。',
  },
]
